
import { getPagination } from "@/utils/pagination";
import PostList from "../../components/PostList";
import PostPagination from "../../components/PostPagination";

import { allPosts,Post } from "contentlayer/generated"

const posts: Post[] = allPosts.sort((a, b) => b.date.localeCompare(a.date));

export const metadata = {
  title: "Lista de todos los post",
  descripcion: "Description posts - Generated by create next app"
}

const Posts = () => {

  const { currentPosts,totalPages } = getPagination(posts)

  return (
    <div>

     
      <div className="grid gap-4">
        <PostList posts={currentPosts} />
        {totalPages > 1 && <PostPagination totalPages={totalPages} currentPage={1} />}
      </div>
    </div>
  )
}

export default Posts